### ISSUE TITLE
`suppress_output` isn't compatible with Windows, causing install-at-import to fail

### ISSUE THREAD

**Issue by dap-biospec** [AUTODIAL/AutoEIS#96] opened 2024-03-01 22:09 UTC
Fresh installation using:

```shell
pip install -U autoeis
... [success] 
```

followed by:

```python
import numpy as np
import autoeis as ae
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\Python312\Lib\site-packages\autoeis\__init__.py", line 1, in <module>
    from . import core, io, metrics, parser, utils, visualization  # noqa: F401, E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ....
  File "D:\Python\Python312\Lib\site-packages\juliapkg\install_julia.py", line 23, in log
    print(prefix, *args)
OSError: [WinError 1] Incorrect function
[juliapkg] Locating Julia ^1.6.1

 # Load test dataset shipped with AutoEIS
 Z, freq = ae.io.load_test_dataset()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ae' is not defined
```

Same behavior with standalone or Microsoft store installation; with or without Julia pre-installed. 

Recommendations?

**Comment by ma-sadeghi** [comment] 2024-03-22 20:22
@dap-biospec Sorry for the late reply. Not sure about the root cause, but I believe this should now be fixed. Could you please give it another try? (ideally in a fresh virtualenv just in case)

**Comment by ma-sadeghi** [comment] 2024-03-25 11:06
Since our automated tests are currently passing for the combination of Windows and Python 3.12, I'll close this issue, but feel free to re-open if you still can't import `autoeis`.

**Comment by dap-biospec** [comment] 2024-03-31 21:55
@ma-sadeghi  Package us is now locating Julia versions "~1.6.1, ~1.7, ~1.8, ~1.9, =1.10.0"  but returns the same "OSError: [WinError 1] Incorrect function." Subsequent code returns "name 'ae' is not defined"

**Comment by ma-sadeghi** [comment] 2024-04-01 01:40
@dap-biospec What Python distribution do you use? Anaconda, Pyenv, etc., or did you download it directly from Python.org?

**Closed** 2024-04-01 15:52 UTC

**Comment by ma-sadeghi** [comment] 2024-04-01 15:55
@dap-biospec Sorry for the frustration. I got my hands on a Windows machine this morning, and figured out the root cause. It's now fixed, please upgrade `autoeis`, and should be good to go.

PS. The reason our Windows CI was not failing was because we were using the CLI approach to install Julia dependencies (`python -m autoeis install`), which worked fine, but the install-at-first-import didn't, which wasn't tested. Now, all CIs install Julia dependencies at import, so it's now fully covered in case something goes wrong in the future.
